# Generated by Django 4.2 on 2023-05-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateName', models.CharField(blank=True, max_length=100, null=True)),
                ('cateImage', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
