# Generated by Django 4.2 on 2023-05-02 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModernApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydb',
            name='cateImage',
        ),
    ]
