# Generated by Django 3.2.10 on 2023-05-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModernApp', '0003_categorydb_cateimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='productDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProName', models.CharField(blank=True, max_length=100, null=True)),
                ('ProPrice', models.IntegerField(blank=True, null=True)),
                ('ProDescription', models.CharField(blank=True, max_length=1000, null=True)),
                ('ProQuantity', models.IntegerField(blank=True, null=True)),
                ('ProImage', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
