# Generated by Django 3.2.10 on 2023-05-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModernApp', '0004_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Procate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
