# Generated by Django 3.2.10 on 2023-05-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModernApp', '0006_rename_productdb_productdb2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=30, null=True)),
                ('ProductCategory', models.CharField(blank=True, max_length=30, null=True)),
                ('ProductPrice', models.IntegerField(blank=True, null=True)),
                ('ProductDescription', models.CharField(blank=True, max_length=1500, null=True)),
                ('ProductQuantity', models.IntegerField(blank=True, null=True)),
                ('ProductImage', models.ImageField(upload_to='profile')),
            ],
        ),
        migrations.DeleteModel(
            name='productDB2',
        ),
    ]
