# Generated by Django 3.2.10 on 2023-06-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModernApp', '0007_auto_20230518_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('Cname', models.CharField(blank=True, max_length=100, null=True)),
                ('Cemail', models.EmailField(blank=True, max_length=100, null=True)),
                ('Csubject', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
